METALLIC = "silver";

WIDTH = 19.8;
SLIM_BOARD_HEIGHT = 0.8;
SLIM_BOARD_LENGTH = 33.8;

FAT_BOARD_LENGTH = 30.5;
FAT_BOARD_HEIGHT = 2;

FRONT_CONNECTOR_LENGTH = 6.7;
FRONT_CONNECTOR_WIDTH = 7.9;
FRONT_CONNECTOR_HEIGHT = 2.8;

REAR_CONNECTOR_LENGTH = 6.1;
REAR_CONNECTOR_WIDTH = 4.4;
REAR_CONNECTOR_HEIGHT = 4.1;


HOLDER_LENGTH = 3;
HOLDER_WIDTH = 3;
HOLDER_HEIGHT = 2;
